-- AUTO-GENERATED BY schema-ddl DO NOT EDIT
-- Generator: schema-ddl 0.1.0
-- Generated: 2015-10-05 11:37

-- Source: iglu:org.ietf/http_cookie/jsonschema/1-0-0

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.org_ietf_http_cookie_1 (
    "schema_vendor"  VARCHAR(128)   NOT NULL,
    "schema_name"    VARCHAR(128)   NOT NULL,
    "schema_format"  VARCHAR(128)   NOT NULL,
    "schema_version" VARCHAR(128)   NOT NULL,
    "root_id"        CHAR(36)             NOT NULL,
    "root_tstamp"    TIMESTAMP            NOT NULL,
    "ref_root"       VARCHAR(255)   NOT NULL,
    "ref_tree"       VARCHAR(1500)  NOT NULL,
    "ref_parent"     VARCHAR(255)   NOT NULL,
    "name"           VARCHAR(4096)                  NOT NULL,
    "value"          VARCHAR(4096),

    CONSTRAINT http_cookie_1__root_id_pk PRIMARY KEY(root_id),
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
);
-- DISTSTYLE KEY
-- DISTKEY (root_id)
-- SORTKEY (root_tstamp);

CREATE INDEX http_cookie_1__root_tstamp_idx ON atomic.org_ietf_http_cookie_1 (root_tstamp);